### ISSUE TITLE
Password reset link

### ISSUE THREAD

**Issue by nettsite** [DanTheDJ/multitenant#12]
Does anyone have any guidance for me on how to correct the password reset link in the email sent to users when they forget their password?

The link is to http://example.com instead of http://tenant.example.com.

**Comment by DanTheDJ** [comment]
Hi @NettSite, apoligies for the delay in getting back to you.

I managed to override the default behavior, this should work for you. I need to sit down when I have some time to have a look at this library as there are a few missing use cases which I would like to work as standard.

https://gist.github.com/DanTheDJ/e2d129e546af1bf53799349ecc2d8c41

**Comment by DanTheDJ** [comment]
PS: You'll need to change the link inside the '->action()' call.

**Comment by nettsite** [comment]
Thanks. I had managed to figure it out, I should have closed the issue.
