### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by simondotwhite** [DanTheDJ/multitenant#2]
Hey,

I've had a play around with and out of the box it resolves the tenant or throws an exception. 

In my case I have it using middleware and a custom service provider to make sure the tenant for certain routes/groups. 

Would you be interested in me creating a pull request to add this functionality?

**Comment by DanTheDJ** [comment]
Hi, I'm more than happy for you to do this, to be fair I haven't had time to work on this lately. Go ahead

**Comment by DanTheDJ** [comment]
@Sekonda regarding your recent PR, great job and thanks a lot. How does this play with PHPUnit testing?
