### ISSUE TITLE
Is there anyway we can switch between prefix or multi database approach?

### ISSUE THREAD

**Issue by xyrintech** [DanTheDJ/multitenant#6]

**Comment by DanTheDJ** [comment]
Hi, what do you mean by prefix?

**Comment by xyrintech** [comment]
I mean table_prefix

I have been looking for table wherein I can specify whether we need to create multiple databases or have the table prefix.

**Comment by DanTheDJ** [comment]
You would really want to use one or the other for your project. It could get confusing having both prefixed tables and databases

**Comment by xyrintech** [comment]
Got it.
